name: "franka-emika-rl"
services:
  fep_rl:
    image: fep_rl
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: fep_rl
    volumes:
      - ..:/code
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev:/dev:rw
      - ${HOME}/.Xauthority:${HOME}/.Xauthority:ro
    devices:
      - /dev/dri:/dev/dri
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=${XAUTHORITY:-${HOME}/.Xauthority}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISABLE_ROS1_EOL_WARNINGS=1
    expose:
      - "20210-20230/udp"
      - "33300-33400/udp"
      - "5559"
    ports:
      - "20210-20230:20210-20230/udp"
      - "33300-33400:33300-33400/udp"
      - "5559:5559"
    network_mode: host
    ipc: host
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 99
      memlock: -1


  safe_learning:
    image: safe_learning
    build:
      context: ..
      dockerfile: docker/Dockerfile.safe_learning
    container_name: safe_learning
    volumes:
      - ..:/workspace
    working_dir: /workspace/external/safe-learning
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    network_mode: "host"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    tty: true
    stdin_open: true
